---
- hosts: jira
  become: true
  pre_tasks:
    - name: install packages required for testing
      yum: name={{ item }} state=present
      with_items:
        - libselinux-python
        - net-tools
    - name: disable selinux during testing
      selinux: policy=targeted state=permissive

  roles:
    - { role: williamyeh.oracle-java, tags: ['skip_ansible_lint'] }
    - role: ansible-role-jira


  vars:
    java_version: 8
    java_subversion: 102
    # NOTE: download jdk-8u102-linux-x64.rpm to files/ for faster testing
    java_download_from_oracle: false
    jira_manage_service: true
    # NOTE: download JIRA package in files/ for faster testing
    jira_download_from_remote: false
