---
- hosts: all
  become: true
  pre_tasks:
    - name: install packages required for testing
      yum: name={{ item }} state=present
      with_items:
        - libselinux-python
        - net-tools
    - name: disable selinux during testing
      selinux: policy=targeted state=permissive

  roles:
    - role: williamyeh.oracle-java
    - role: ansible-role-jira


  vars:
    # NOTE: Use pre-downloaded JIRA package in files/
    jira_download_from_atlassian: false
    java_version: 8
    java_subversion: 101
    # NOTE: For speedy testing, download jdk-8u92-linux-x64.rpm to files/
    java_download_from_oracle: false
    jira_manage_service: true
