---
- name: config > jira-application.properties
  template:
    src: jira-application.properties.j2
    dest: "{{ jira_install_dir }}/{{ jira_version }}/atlassian-jira/WEB-INF/classes/jira-application.properties"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0444

- name: config > server.xml
  template:
    src: server.xml.j2
    dest: "{{ jira_install_dir }}/{{ jira_version }}/conf/server.xml"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0444

- name: config > setenv.sh
  template:
    src: setenv.sh.j2
    dest: "{{ jira_install_dir }}/{{ jira_version }}/bin/setenv.sh"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0444

