---
- name: config > jira-application.properties
  template:
    src: jira-application.properties.j2
    dest: "{{ jira_install_dir }}/{{ jira_version }}/atlassian-jira/WEB-INF/classes/jira-application.properties"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0444

# For HTTPS configuration. Not applied for now
- name: config > server.xml
  template:
    src: server.xml.j2
    dest: "{{ jira_install_dir }}/{{ jira_version }}/conf/server.xml"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0444

- name: config > systemd directory
  file: path=/etc/systemd/system state=directory

- name: config > systemd manifest
  template:
    src: jira.service.j2
    dest: "/etc/systemd/system/jira.service"
    owner: root
    group: root
    mode: 0444
